# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180810_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashes',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
