# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-12 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_auto_20180811_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashes', models.TextField(blank=True, verbose_name='Hashes')),
                ('user_ip', models.CharField(blank=True, max_length=256, verbose_name='IP address')),
                ('user_browser', models.CharField(blank=True, max_length=256, verbose_name='Browser')),
                ('user_oc', models.CharField(blank=True, max_length=256, verbose_name='OC')),
                ('user_device', models.CharField(blank=True, max_length=256, verbose_name='Device')),
                ('user_timezone', models.CharField(blank=True, max_length=256, verbose_name='Timezone')),
                ('user_country', models.CharField(blank=True, max_length=256, verbose_name='Country')),
                ('user_city', models.CharField(blank=True, max_length=256, verbose_name='City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'Users Informations',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
    ]
